version: '3.9'
services:
  es-node01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    container_name: es-node01
    environment:
      - node.name=es-node01
      - cluster.name=es-cluster-8
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - es-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.0
    environment:
      ELASTICSEARCH_HOSTS: http://es-node01:9200
    ports:
      - 5601:5601
    networks:
      - es-network
    depends_on:
      - es-node01

volumes:
  es-data01:
    driver: local

networks:
  es-network:
    driver: bridge
